import { initializeApp } from 'firebase/app';
import { getAuth, GoogleAuthProvider, signInWithPopup } from 'firebase/auth';
import { getFirestore, collection, addDoc, updateDoc, deleteDoc, doc, onSnapshot, query, where, orderBy, getDocFromServer } from 'firebase/firestore';

// We wrap in a try-catch because the config might be missing initially
let db: any;
let auth: any;
let googleProvider: any;

try {
  // @ts-ignore - this file is generated by the set_up_firebase tool
  import firebaseConfig from '../../firebase-applet-config.json';
  const app = initializeApp(firebaseConfig);
  db = getFirestore(app, firebaseConfig.firestoreDatabaseId);
  auth = getAuth(app);
  googleProvider = new GoogleAuthProvider();
} catch (e) {
  console.warn("Firebase config not found. Please complete the setup in the UI.");
}

export { db, auth, googleProvider };

// Helper to test connection (from skill)
export async function testConnection() {
  if (!db) return;
  try {
    await getDocFromServer(doc(db, 'test', 'connection'));
  } catch (error) {
    if (error instanceof Error && error.message.includes('the client is offline')) {
      console.error("Please check your Firebase configuration.");
    }
  }
}

export const OperationType = {
  CREATE: 'create',
  UPDATE: 'update',
  DELETE: 'delete',
  LIST: 'list',
  GET: 'get',
  WRITE: 'write',
} as const;

export interface FirestoreErrorInfo {
  error: string;
  operationType: typeof OperationType[keyof typeof OperationType];
  path: string | null;
  authInfo: any;
}

export function handleFirestoreError(error: unknown, operationType: typeof OperationType[keyof typeof OperationType], path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth?.currentUser?.uid,
      email: auth?.currentUser?.email,
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}
